version: "3"

services:
  db:
    container_name: catalog-app
    image: mongo:3.4
    networks:
      - main
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  web:
    depends_on:
      - db
    build: .
    image: catalog_app
    ports:
      - 9001:9001
    networks:
      - main
    volumes:
      - ./:/www/app
    environment:
      PORT: 9001
      DATABASE_URL: mongodb://db:27017/catalogapp
      NODE_ENV: development
    command: npm start

volumes:
  data:

networks:
  main:
    driver: bridge
