version: "3"
services:
  db:
    restart: always
  web:
    ports:
      - 80:80
    environment:
      NODE_ENV: production
      DATABASE_URL: mongodb://db:27017/catalogapp
    command: npm run start:prod
